version: "3.1"
services:
  image: mongo
  restart: always
  environment:
    MONGO_INITDB_ROOT_USERNAME: root
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 27017: 27017
