FROM php:8.0-cli
RUN apt-get update \
    && apt-get install -y \
    git \
    unzip \
    libzip-dev \
    && docker-php-ext-install zip bcmath
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
WORKDIR /app
COPY composer.json composer.lock /app/
RUN composer install --no-scripts --no-autoloader
COPY . /app
CMD ["php", "-S","0.0.0.0:5003","-t","public"]